name: donations - CI

on:
  push:
    branches: [ "main" ]
    tags:
        - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Grant execute permissions
      run: chmod +x ${{ github.workspace }}/PixelMCDonations/PixelMCDonations/gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build
      working-directory: ${{ github.workspace }}/PixelMCDonations/PixelMCDonations
    
    - name: Upload Drop
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: pixelmcdonations
        path: |
          PixelMCDonations/PixelMCDonations/build/libs
  
  publish_release: 
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Download Drop
        uses: actions/download-artifact@v4
        with:
          name: pixelmcdonations
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: '**/*.jar'
    

